WIP Test setup
ekr/dnssec-interference pull request #6
Opened 2022-10-31 20:13 UTC by k88hudson

2022-11-01 18:19 UTC, k88hudson commented on src/dns-test.js
> +    if (perClient) {
I moved this to the end so it was easier to test for per-client queries systematically

2022-11-04 10:43 UTC, ekr requested changes

2022-11-04 10:43 UTC, ekr commented on src/dns-test.js
> +// For tests
Would it be better to instead have all these be inside some object that is instantiated afresh, rather than as globals?

2022-11-04 10:43 UTC, ekr commented on src/dns-test.js
> +        dnsAttempts[key] = dnsAttempts[key] || 0 + 1
I think this code is wrong because + has higher precedence than  ||, so it becomes:

`
dnsAttempts[key] || (0 + 1)
` 
Which reduces to `dnsAttempts[key] || 1` which in practice is going to be `1`.

More generally, I hate having to look up precedence tables, so let's just put in parentheses so it's clear.


More generally, I hate looking at precedence table

2022-11-04 10:43 UTC, ekr commented on src/dns-test.js
> +                console.error(e);
logMessage

2022-11-04 10:43 UTC, ekr commented on src/dns-test.js
> +            console.error(e);
logMessage.

2022-11-04 10:43 UTC, ekr commented on src/dns-test.js
> +    if (perClient) {
SG

2022-11-04 10:43 UTC, ekr commented on src/dns-test.js
> +    assert(transport in sendDNSQuery, `${transport} is not a valid transport type`);
Nice. Obviously, I have C++ programmer's disease so I didn't think of this,

2022-11-04 10:43 UTC, ekr commented on test/dns-test.test.js
> + * A non-exhaustive list of queries/domains to check to mak sure we're computing
```suggestion
 * A non-exhaustive list of queries/domains to check to make sure we're computing
```

2022-11-04 10:43 UTC, ekr commented on test/dns-test.test.js
> +describe("dns-test.js", () => {
How are you going to refactor this to allow for failures?

2022-11-04 12:09 UTC, k88hudson commented on src/dns-test.js
> +// For tests
Yes, definitely – although I was planning on minimizing the size of this PR and doing it as part of #11 since we need to start storing errors at that point.

2022-11-04 12:18 UTC, k88hudson commented on src/dns-test.js
> +                console.error(e);
in this case I'd like it to log the actual error + the stack and I think it would be appropriate in production (since it's an error). What do you think? I could make a `logError` dependent on it being local as well.

2022-11-04 12:19 UTC, k88hudson commented on test/dns-test.test.js
> +describe("dns-test.js", () => {
What do you mean allow for failures?

2022-11-04 12:19 UTC, k88hudson commented on src/dns-test.js
> +        dnsAttempts[key] = dnsAttempts[key] || 0 + 1
Good catch

2022-11-13 14:18 UTC, ekr commented on src/dns-test.js
> +async function main({uuid = uuidv4()} = {}) {
Obviously I don't know enough JS, What the heck does this do?

2022-11-13 14:21 UTC, k88hudson commented on src/dns-test.js
> +async function main({uuid = uuidv4()} = {}) {
the equivalent is:
```
function main(options) {
  options = options || {};
  let uuid = options.uuid || uuidv4();
}
```

2022-11-13 14:23 UTC, k88hudson commented on src/dns-test.js
> +async function main({uuid = uuidv4()} = {}) {
it assigns a default value if the parameter is `undefined`

2022-11-13 14:25 UTC, merged